### ISSUE TITLE
图片不显示的问题

### ISSUE THREAD

**Issue by moyunmo** [littleMeaning/LMNote#1]
感谢开源。
有一个问题，当编辑两份或以上的文章后，   第一次编辑保存再打开没问题， 编辑第二篇文章后保存再打开第一篇，第一篇文章的图片不显示，我找了半天没发现原因， 作者能帮忙指点一下吗？

清空缓存的时候 沙盒里面对应的文件也没有清理干净

**Comment by moyunmo** [comment]
判断是草稿进来的把LMNImageView置空重新赋值 目前可以 解决图片不展示的问题

**Comment by DanielDanielDanielDaniel** [comment]
> 感谢开源。
> 有一个问题，当编辑两份或以上的文章后， 第一次编辑保存再打开没问题， 编辑第二篇文章后保存再打开第一篇，第一篇文章的图片不显示，我找了半天没发现原因， 作者能帮忙指点一下吗？
> 
> 清空缓存的时候 沙盒里面对应的文件也没有清理干净

有解决后的码流么
